platform :ios, '10.0'

target 'AudioRecording' do
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'BubbleTransition'
  pod 'SCSiriWaveformView'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'InputMask'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'BGTableViewRowActionWithImage'

end
